"use client";

import type { PartySparkCard } from "@/lib/party-spark-types";

type ShareIdeaCardProps = {
  card: PartySparkCard;
  brandLine?: string;
};

/** Copy-friendly share block (not an image asset — keeps page light) */
export function ShareIdeaCard({ card, brandLine = "Connecticut Party Rentals" }: ShareIdeaCardProps) {
  return (
    <div className="rounded-2xl border border-[#E6E1D8] bg-[#FFFCF7] p-4 text-left">
      <p className="text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Party name</p>
      <p className="mt-1 font-[family-name:var(--font-display)] text-lg font-semibold text-[#111111]">{card.partyName}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Event type</p>
      <p className="mt-1 text-sm text-[#555555]">{card.eventTypeLabel}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Tone</p>
      <p className="mt-1 text-sm text-[#555555]">{card.vibeLabel}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Vibe</p>
      <p className="mt-1 text-sm text-[#555555]">{card.contextLine}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Audience</p>
      <p className="mt-1 text-sm text-[#555555]">{card.audienceLabel}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Guests</p>
      <p className="mt-1 text-sm text-[#555555]">{card.guestCountLabel}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Best for</p>
      <p className="mt-1 text-sm text-[#555555]">{card.bestFor}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Theme name</p>
      <p className="mt-1 text-sm text-[#555555]">{card.themeName}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Theme details</p>
      <p className="mt-1 text-sm text-[#555555]">{card.themeLine}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Mood</p>
      <p className="mt-1 text-sm text-[#555555]">{card.moodChips.join(" · ")}</p>
      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.12em] text-[#777777]">Invite line</p>
      <p className="mt-1 text-sm italic text-[#111111]">&ldquo;{card.inviteLine}&rdquo;</p>
      <p className="mt-4 text-[11px] text-[#777777]">Generated by {brandLine}</p>
    </div>
  );
}

export function formatShareText(card: PartySparkCard, brandLine: string): string {
  const playbookPreview = card.playbook.slice(0, 2).join("\n• ");
  return `Party name:\n${card.partyName}\n\nEvent type:\n${card.eventTypeLabel}\n\nTone:\n${card.vibeLabel}\n\nVibe:\n${card.contextLine}\n\nAudience:\n${card.audienceLabel}\n\nGuests:\n${card.guestCountLabel}\n\nBest for:\n${card.bestFor}\n\nTheme name:\n${card.themeName}\n\nTheme details:\n${card.themeLine}\n\nMood:\n${card.moodChips.join(" · ")}\n\nTry this:\n• ${playbookPreview}\n\nLook & sound:\n${card.visualMood}\n\nWhy it works:\n${card.whyItWorks}\n\nInvite line:\n"${card.inviteLine}"\n\nSuggested setup:\n${card.setupIdea}\n\nHashtag:\n${card.hashtag}\n\nGenerated by ${brandLine}`;
}
